// Generated by CoffeeScript 1.6.3
(function() {
  jQuery(function($) {
    $(".datetime").datepicker({
      dateFormat: 'yy-mm-dd',
      changeMonth: true,
      changeYear: true,
      yearRange: "-100: +0"
    });
    return $(".submit").click(function(event) {
      var button, form, info;
      button = $(this);
      event.preventDefault();
      form = button.parents("form");
      info = form.serialize() + ("&redirect=" + (button.data("redirect")));
      return $.ajax({
        url: form.attr("action"),
        data: info,
        dataType: "json",
        type: "POST",
        success: function(data) {
          var errorlabel, field, fieldcont, message, _ref, _results;
          if (data.msgclass === "alert-success") {
            $.loadPage(data.direction);
            return $.showMessage(data.msg, data.msgclass);
          } else {
            _ref = $.parseJSON(data.msg);
            _results = [];
            for (field in _ref) {
              message = _ref[field];
              fieldcont = $("#div-id-" + field);
              errorlabel = $("<label></label>").addClass("error-label").html(message);
              _results.push(fieldcont.addClass("has-error").append(errorlabel));
            }
            return _results;
          }
        }
      });
    });
  });

}).call(this);
