// Generated by CoffeeScript 1.8.0
(function() {
  jQuery(function($) {
    $("body").on("click", ".msglink", function(e) {
      var link;
      link = $(this);
      e.preventDefault();
      if (link.hasClass("confirm")) {
        if (confirm("Вы уверены, что хотите удалить запись?")) {
          return $.ajax({
            url: link.attr("href"),
            type: "GET",
            dataType: "json",
            success: function(data) {
              $.showMessage(data.msg, data.msgclass);
              if (data.action === "remove") {
                return $(link.data("record")).fadeOut("slow");
              }
            }
          });
        }
      } else {
        return $.ajax({
          url: link.attr("href"),
          type: "GET",
          dataType: "json",
          success: function(data) {
            $.showMessage(data.msg, data.msgclass);
            if (data.action === "remove") {
              return $(link.data("record")).remove();
            }
          }
        });
      }
    });
    $("body").on("click", ".savelink", function(e) {
      var field, link;
      link = $(this);
      field = $(link.data("fieldname"));
      e.preventDefault();
      return $.ajax({
        url: link.attr("href"),
        type: "POST",
        data: field.find(":input").serialize(),
        dataType: "json",
        success: function(data) {
          $(data.toappend).appendTo($(link.data("record")));
          field.find(":input").val("");
          return $.showMessage(data.msg, data.msgclass);
        }
      });
    });
    $("body").on("click", ".savecomment", function(e) {
      var form, item;
      e.preventDefault();
      item = $(this);
      form = item.parent("form");
      return $.ajax({
        url: form.attr("action"),
        data: form.serialize(),
        type: "POST",
        success: function(data) {
          form.find(":input").each(function() {
            if ($(this).attr("type") !== "hidden" && !$(this).hasClass("noclear")) {
              return $(this).val("");
            }
          });
          return $(data).prependTo($(item.data("container")));
        }
      });
    });
    $("body").on("click", ".mainId", function() {
      var item;
      item = this;
      $(".mainId").removeProp("checked");
      return item.checked = true;
    });
    return $("#logout").click(function() {
      return $.post("/user/logout", function() {
        window.location.hash = "";
        return window.location.href = "/";
      });
    });
  });

}).call(this);

//# sourceMappingURL=main.js.map
