// Generated by CoffeeScript 1.8.0
(function() {
  jQuery(function($) {
    $(".datetime").datepicker();
    $(".dateyear").datepicker({
      changeMonth: true,
      changeYear: true,
      yearRange: "-100: +0",
      defaultDate: "-18y"
    });
    $(".maintour").click(function(e) {
      var form, info, wishes;
      e.preventDefault();
      form = $(this).parents("form");
      wishes = $("#wishes").find(":input");
      info = form.add(wishes).serialize() + ("&redirect=" + ($(this).data("redirect")));
      $(".form-tourist").not("#tourist-new").find(".save-new").trigger("click");
      return $.ajax({
        url: form.attr("action"),
        data: info,
        type: "POST",
        dataType: "json",
        success: function(data) {
          if (data.msgclass === "alert-success") {
            $.loadPage(data.direction);
          }
          return $.showMessage(data.msg, data.msgclass);
        }
      });
    });
    $("#directions").change(function() {
      return $.ajax({
        url: "/orders/getoffers",
        data: {
          id: $(this).val()
        },
        type: "POST",
        dataType: "json",
        success: function(data) {
          var item, orders, _i, _len, _results;
          orders = $("#offers").html("");
          _results = [];
          for (_i = 0, _len = data.length; _i < _len; _i++) {
            item = data[_i];
            _results.push($("<option></option>").val(item.id).html(item.text).appendTo(orders));
          }
          return _results;
        }
      });
    });
    $("#sinput").autocomplete({
      source: function(request, response) {
        return $.ajax({
          url: "/orders/search",
          dataType: "json",
          data: {
            search: $("#sinput").val()
          },
          type: "POST",
          success: function(data) {
            return response(data);
          }
        });
      },
      minLength: 3,
      select: function(event, ui) {
        $(".searchform").find("input").val("");
        $.ajax({
          url: "/orders/gettourist",
          data: {
            id: ui.item.value
          },
          type: "POST",
          dataType: "json",
          success: function(data) {
            var name, value, _results;
            _results = [];
            for (name in data) {
              value = data[name];
              _results.push($("#new-" + name).val(value));
            }
            return _results;
          }
        });
        return false;
      }
    });
    $(".search").click(function() {
      return $(".searchform").toggle();
    });
    $(".find-tour").click(function() {
      return $(".find-tour-list").toggle();
    });
    return $(".find-tour-item").click(function() {
      var item;
      item = $(this);
      $(".find-tour-list").hide();
      $("#order-date").val(item.data("date"));
      return $("#tour-offer").val(item.data("offer"));
    });
  });

}).call(this);

//# sourceMappingURL=order.js.map
