// Generated by CoffeeScript 1.6.3
(function() {
  jQuery(function($) {
    $(".datepick").datepicker({
      dateFormat: "dd.mm.yy",
      onSelect: function(date, ui) {
        var cdate;
        cdate = new Date();
        return $("#ctime").val(date + " " + cdate.getHours() + ":" + cdate.getMinutes());
      }
    });
    return $(".payments").on("click", ".delete-payment", function(e) {
      var container, item;
      e.preventDefault();
      item = $(this);
      container = item.parents("tr");
      return $.ajax({
        url: item.attr("href"),
        data: {
          id: item.data("id")
        },
        type: "POST",
        dataType: "JSON",
        success: function(data) {
          $(".rest").html(data.rest);
          $(".payment").html(data.price);
          if (container != null) {
            $(container).fadeOut("slow").remove();
          }
          return $.showMessage(data.message, data.type);
        }
      });
    });
  });

}).call(this);
