// Generated by CoffeeScript 1.7.1
(function() {
  jQuery(function($) {
    $(".tourist-accordion").accordion({
      heightStyle: "content",
      collapsible: true
    });
    $(".service-drag").draggable({
      revert: function() {
        return $(this).data("uiDraggable").originalPosition;
      },
      revertDuration: 1
    });
    $("#orderContainer").on("click", ".save-service", function(e) {
      var container, form, item, serviceComment, servicePrice;
      e.preventDefault();
      item = $(this);
      form = item.parents("form");
      container = item.data("container");
      servicePrice = form.find(".service-price").find("input").val();
      serviceComment = form.find(".service-comment").find("input").val();
      if (servicePrice !== "0" && serviceComment === "") {
        return alert("Введите комментарий");
      } else {
        return $.ajax({
          url: form.attr("action"),
          type: "POST",
          dataType: "JSON",
          data: form.serialize(),
          success: function(data) {
            if (data.type === "alert-success") {
              if (!$("#priceValue").hasClass("fixed")) {
                $("#priceValue").html(data.price);
              }
            }
            if (container != null) {
              $(container).append(data.body);
            }
            $.showMessage(data.message, data.type);
            if (form.attr("action") === "/orders/addaservice") {
              return form.find(":input").each(function() {
                if ($(this).attr("type") !== "hidden") {
                  return $(this).val("");
                }
              });
            }
          }
        });
      }
    });
    $("#orderContainer").on("click", ".delete-service", function(e) {
      var container, item;
      e.preventDefault();
      item = $(this);
      container = item.data("container");
      return $.ajax({
        url: item.attr("href"),
        data: {
          id: item.data("id")
        },
        type: "POST",
        dataType: "JSON",
        success: function(data) {
          if (data.type === "alert-success" && !$("#priceValue").hasClass("fixed")) {
            $("#priceValue").html(data.price);
          }
          if (container != null) {
            $(container).fadeOut("slow").remove();
          }
          return $.showMessage(data.message, data.type);
        }
      });
    });
    $(".tourist-block").droppable({
      hoverClass: "ui-state-active"
    });
    $(".tourist-block").on("drop", function(event, ui) {
      var container, header, service;
      service = ui.draggable;
      header = $(this);
      container = $("#" + header.attr("id") + "+.service-list");
      return $.ajax({
        url: "/orders/addservice",
        type: "POST",
        data: {
          "data[touristId]": header.data("id"),
          "data[serviceId]": service.data("id"),
          "data[orderId]": $("#orderId").val()
        },
        dataType: "json",
        success: function(data) {
          if (data.type === "alert-success") {
            container.append(data.body);
            if (!$("#priceValue").hasClass("fixed")) {
              $("#priceValue").html(data.price);
            }
            header.find("small").append(", " + data.name);
          }
          return $.showMessage(data.message, data.type);
        }
      });
    });
    $(".tourist-add-all").droppable({
      hoverClass: "ui-state-active",
      drop: function(event, ui) {
        return $(".tourist-block").trigger("drop", ui);
      }
    });
    return $("#recalculateCost").click(function() {
      return $.ajax({
        url: "/orders/recalculate",
        data: {
          id: $("#orderId").val()
        },
        dataType: "json",
        type: "GET",
        success: function(data) {
          if (data.price != null) {
            $("#priceValue").html(data.price);
          }
          return $.showMessage(data.message, data.type);
        }
      });
    });
  });

}).call(this);

//# sourceMappingURL=services.map
