// Generated by CoffeeScript 1.6.3
(function() {
  jQuery(function($) {
    var hotelopts, options, vehicleopts;
    $("#tourComment").click(function(e) {
      e.preventDefault();
      return $.post("/tours/savetourcomment", {
        comment: $("#tourCommentInput").val(),
        id: $("#tourId").val()
      }, function(data) {
        return $.showMessage(data.message, data.type);
      }, "json");
    });
    vehicleopts = {
      hoverClass: "hover-background",
      drop: function(event, ui) {
        var container, tourist, touristId, touristOld, ttId;
        tourist = ui.draggable;
        container = $(this);
        ttId = container.data("transport");
        touristId = tourist.data("tourist");
        touristOld = tourist.data("old");
        return $.ajax({
          url: "/tours/updatetransport",
          data: {
            "data[touristId]": touristId,
            "data[newttId]": ttId,
            "data[ttId]": touristOld
          },
          type: "POST",
          dataType: "json",
          success: function(data) {
            var free, num, vehicle, vehicleId;
            if (data.type !== "remove") {
              tourist.hide();
              $("#vehicle-tourists-" + ttId).append($(data.element).draggable(options));
              $("#transport-for-" + touristId).html(data.vehicleName);
              vehicle = $("#vehicle-container-" + ttId);
              num = parseInt(vehicle.find(".toupdate").html());
              vehicle.find(".toupdate").html(num + 1);
              free = parseInt(vehicle.find(".free").html());
              return vehicle.find(".free").html(num - 1);
            } else {
              vehicleId = tourist.parents(".vehicle-droppable").data("transport");
              vehicle = $("#vehicle-container-" + vehicleId);
              tourist.hide();
              $("#vehicle-empty").append($(data.element).draggable(options));
              $("#transport-for-" + touristId).html("Не выбрано");
              num = parseInt(vehicle.find(".toupdate").html());
              vehicle.find(".toupdate").html(num - 1);
              free = parseInt(vehicle.find(".free").html());
              return vehicle.find(".free").html(num + 1);
            }
          }
        });
      }
    };
    hotelopts = {
      hoverClass: "hover-background",
      drop: function(event, ui) {
        var container, thId, tourist, touristId, touristOld;
        tourist = ui.draggable;
        container = $(this);
        thId = container.data("hotel");
        touristId = tourist.data("tourist");
        touristOld = tourist.data("oldhotel");
        return $.ajax({
          url: "/tours/updatehotel",
          data: {
            "data[touristId]": touristId,
            "data[newthId]": thId,
            "data[thId]": touristOld
          },
          type: "POST",
          dataType: "json",
          success: function(data) {
            var hotel, hotelId, num;
            if (data.type !== "remove") {
              tourist.hide();
              $("#hotel-tourists-" + thId).append($(data.element).draggable(options));
              $("#hotel-for-" + touristId).html(data.hotelName);
              hotel = $("#hotel-container-" + thId);
              num = parseInt(hotel.find(".toupdate").html());
              return hotel.find(".toupdate").html(num + 1);
            } else {
              hotelId = tourist.parents(".hotel-droppable").data("hotel");
              hotel = $("#hotel-container-" + hotelId);
              tourist.hide();
              $("#hotel-empty").append($(data.element).draggable(options));
              $("#hotel-for-" + touristId).html("Не выбрано");
              num = parseInt(hotel.find(".toupdate").html());
              return hotel.find(".toupdate").html(num - 1);
            }
          }
        });
      }
    };
    $("#tourMenu").children(".btn").click(function() {
      var item;
      item = $(this);
      $("#tourMenu").children(".active").removeClass("active");
      item.addClass("active");
      $(item.data("hide")).addClass("hide");
      return $(item.data("show")).removeClass("hide");
    });
    options = {
      helper: function() {
        return $("<div></div>").addClass("tourist-drag-helper").html($(this).data("name"));
      }
    };
    $(".tourist-drag").draggable(options);
    $(".transport-container, .vehicle-droppable").droppable(vehicleopts);
    $(".hotel-container, .hotel-droppable").droppable(hotelopts);
    $("#doAddVehicle").click(function() {
      var button;
      button = $(this);
      return $.ajax({
        url: button.data("href"),
        data: {
          id: $("#addTransport").val(),
          tourId: button.data("id")
        },
        type: "POST",
        dataType: "json",
        success: function(data) {
          $(data.block).appendTo($("#availableTransports")).droppable(vehicleopts);
          return $(data.list).appendTo($("#allVehicles")).droppable(vehicleopts);
        }
      });
    });
    $("#doAddHotel").click(function() {
      var button;
      button = $(this);
      return $.ajax({
        url: button.data("href"),
        data: {
          id: $("#addHotel").val(),
          tourId: button.data("id")
        },
        type: "POST",
        dataType: "json",
        success: function(data) {
          $(data.block).appendTo($("#availableHotels")).droppable(hotelopts);
          return $(data.list).appendTo($("#allHotels")).droppable(hotelopts);
        }
      });
    });
    $("body").on("click", ".removeitem", function() {
      var button;
      button = $(this);
      return $.ajax({
        url: button.data("href"),
        type: "POST",
        dataType: "json",
        data: {
          id: button.data("id")
        },
        success: function(data) {
          var tourist, _i, _len, _results;
          button.parent().parent().remove();
          $("#vehicle-tourists-" + (button.data("id"))).remove();
          _results = [];
          for (_i = 0, _len = data.length; _i < _len; _i++) {
            tourist = data[_i];
            $(tourist.body).appendTo($("#vehicle-empty")).draggable(options);
            _results.push($("#transport-for-" + tourist.id).html("Не выбрано"));
          }
          return _results;
        }
      });
    });
    $("body").on("click", ".removehotel", function() {
      var button;
      button = $(this);
      return $.ajax({
        url: button.data("href"),
        type: "POST",
        dataType: "json",
        data: {
          id: button.data("id")
        },
        success: function(data) {
          var tourist, _i, _len, _results;
          button.parent().parent().remove();
          $("#hotel-tourists-" + (button.data("id"))).remove();
          _results = [];
          for (_i = 0, _len = data.length; _i < _len; _i++) {
            tourist = data[_i];
            $(tourist.body).appendTo($("#hotel-empty")).draggable(options);
            _results.push($("#hotel-for-" + tourist.id).html("Не выбрано"));
          }
          return _results;
        }
      });
    });
    return $("#tourTransport").on("change", ".transport-driver", function() {
      var select;
      select = $(this);
      return $.ajax({
        url: "/tours/adddriver",
        type: "POST",
        dataType: "json",
        data: {
          id: select.parents(".transport-container").data("transport"),
          driverId: select.val()
        },
        success: function(data) {
          $("#driverPhone").html(data.phone);
          return $.showMessage(data.message, data["class"]);
        }
      });
    });
  });

}).call(this);
